feat: add dockerhub monitoring feature
spaceone-dev/plugin-dockerhub-mon-webhook pull request #2
Opened 2022-07-04 04:39 UTC by GeunjeLEE

### Category
- [x] New feature
- [ ] Bug fix
- [ ] Improvement
- [ ] Refactor
- [ ] etc

### Description
dockerhub webhook plugin accepts 'image push(POST)' requests.
you can this plugin to integrate dockerhub event to cause an action

### Known issue

2022-07-04 04:56 UTC, jihyungSong commented
Interface definition content ( `api/webhook.py` ) to handle webhook API `init` and `verify` is required.

2022-07-04 04:57 UTC, jihyungSong requested changes
Interface definition contents ( api/webhook.py ) to handle webhook API init and verify is required.

2022-07-04 05:59 UTC, jihyungSong requested changes

2022-07-04 05:59 UTC, jihyungSong commented on src/spaceone/monitoring/manager/event_manager.py
> +        base_info = {
Why don't pass raw_data directly to `_generate_data()` method, but created `base_info` value and then passed it.

2022-07-04 05:59 UTC, jihyungSong commented on src/spaceone/monitoring/manager/event_manager.py
> +            'rule': rule,
I wonder why you set `repository.full_description` in rule .

2022-07-04 10:20 UTC, GeunjeLEE commented on src/spaceone/monitoring/manager/event_manager.py
> +            'rule': rule,
It's a setting mistake, i will fix it.

2022-07-14 05:43 UTC, GeunjeLEE commented
@whdalsrnt @jihyungSong 
Any other feedback?

2022-07-22 05:11 UTC, merged